In [2]:
import numpy as np
import pandas as pd
import pickle

In [3]:
# Deserialize fk tables
with open('fk_dict.pkl', 'rb') as f:
  fk_tables_dict = pickle.load(f)

# Deserialize central data
with open('central_data_dict.pkl', 'rb') as f:
  central_data_dict = pickle.load(f)

# Deserialize covmat
C = pd.read_pickle('covmat.pkl')

In [ ]:
# example for fk tables
fk_tables_dict['BCDMS_NC_NOTFIXED_D_EM-F2']

<tf.Tensor: shape=(248, 50, 9), dtype=float32, numpy=
array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 9.31731425e-04,  1.39287440e-03,  1.57079543e-19, ...,
          4.67454708e-21,  1.08157605e-04, -1.26715226e-04],
        [ 1.29282847e-03,  1.96197024e-03,  1.92895042e-19, ...,
          4.99430070e-20,  1.39606476e-04, -1.79782524e-04],
        [ 3.55641911e-04,  5.24121395e-04,  4.57396758e-20, ...,
         -4.20202829e-22,  4.48585888e-05, -5.19236892e-05]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.000

In [ ]:
# example for Y
central_data_dict['BCDMS_NC_NOTFIXED_D_EM-F2']

array([0.36575, 0.36092, 0.3536 , 0.35702, 0.34834, 0.33013, 0.34016,
       0.33475, 0.33123, 0.3378 , 0.31451, 0.31298, 0.30061, 0.30601,
       0.30947, 0.29547, 0.29306, 0.27761, 0.28678, 0.27833, 0.27099,
       0.27198, 0.26953, 0.26596, 0.25886, 0.25756, 0.25851, 0.24795,
       0.23909, 0.23758, 0.23279, 0.2345 , 0.23381, 0.22833, 0.21961,
       0.21705, 0.1829 , 0.18873, 0.17893, 0.17382, 0.18531, 0.17836,
       0.17729, 0.17661, 0.17234, 0.16928, 0.16545, 0.16205, 0.12068,
       0.11853, 0.12108, 0.11283, 0.11759, 0.10949, 0.10915, 0.10904,
       0.10842, 0.10518, 0.09777, 0.10295, 0.09701, 0.09586, 0.05714,
       0.06287, 0.0592 , 0.05595, 0.05904, 0.05668, 0.05511, 0.05589,
       0.05493, 0.04965, 0.05175, 0.04983, 0.04681, 0.02861, 0.0237 ,
       0.0246 , 0.02521, 0.02659, 0.02449, 0.02296, 0.02062, 0.02491,
       0.01926, 0.02329, 0.008  , 0.00861, 0.00876, 0.00785, 0.00775,
       0.00707, 0.00651, 0.3742 , 0.3604 , 0.35627, 0.36119, 0.3501 ,
       0.33493, 0.34

In [ ]:
# extract the the uncertainties of a dataset from the full covariance matrix
C.xs(level='dataset', key='BCDMS_NC_NOTFIXED_D_EM-F2').T.xs(level='dataset', key='BCDMS_NC_NOTFIXED_D_EM-F2')

group             DIS NC                                                      \
id                   0             1         2             3             4     
group  id                                                                      
DIS NC 0    1.986957e-04  1.612975e-04  0.000148  1.498133e-04  1.494703e-04   
       1    1.612975e-04  2.054500e-04  0.000153  1.553427e-04  1.538633e-04   
       2    1.484925e-04  1.531219e-04  0.000162  1.438305e-04  1.424682e-04   
       3    1.498133e-04  1.553427e-04  0.000144  1.667543e-04  1.438602e-04   
       4    1.494703e-04  1.538633e-04  0.000142  1.438602e-04  1.671852e-04   
...                  ...           ...       ...           ...           ...   
       249  2.348319e-08  2.869618e-07  0.000002  1.287081e-06  4.770826e-07   
       250 -5.652816e-08 -5.979509e-08  0.000001  1.073367e-06  3.440389e-07   
       251 -1.474185e-07 -3.072188e-07  0.000001  8.940779e-07  2.206730e-07   
       252 -2.101223e-07 -4.368175e-07  0.000001  7.843064e-07  1.384722e-07   
       253 -3.312650e-07 -6.798261e-07  0.000001  5.733760e-07 -1.191501e-08   

group                                                                 ...  \
id               5         6         7             8             9    ...   
group  id                                                             ...   
DIS NC 0    0.000136  0.000136  0.000137  1.362756e-04  1.355128e-04  ...   
       1    0.000138  0.000140  0.000140  1.389195e-04  1.371225e-04  ...   
       2    0.000131  0.000132  0.000132  1.305496e-04  1.289394e-04  ...   
       3    0.000131  0.000133  0.000133  1.313732e-04  1.296572e-04  ...   
       4    0.000130  0.000131  0.000132  1.309612e-04  1.299902e-04  ...   
...              ...       ...       ...           ...           ...  ...   
       249  0.000002  0.000002  0.000002  9.187924e-07  2.152174e-07  ...   
       250  0.000002  0.000002  0.000002  9.153026e-07  2.878459e-07  ...   
       251  0.000002  0.000002  0.000002  8.634330e-07  2.877337e-07  ...   
       252  0.000002  0.000002  0.000001  8.104420e-07  2.608262e-07  ...   
       253  0.000002  0.000002  0.000001  7.054316e-07  2.098962e-07  ...   

group                                                                         \
id               244           245           246           247           248   
group  id                                                                      
DIS NC 0    0.000005  8.242883e-07  6.652487e-07  4.087947e-07  3.039601e-07   
       1    0.000005  2.627722e-06  2.149652e-06  1.294249e-06  1.124016e-06   
       2    0.000006  2.701376e-06  2.497064e-06  2.118032e-06  1.989792e-06   
       3    0.000005  2.883430e-06  2.574152e-06  2.010170e-06  1.870558e-06   
       4    0.000005  1.551675e-06  1.336181e-06  9.728416e-07  8.565712e-07   
...              ...           ...           ...           ...           ...   
       249  0.000002  3.490222e-06  3.333519e-06  3.055534e-06  3.022734e-06   
       250  0.000002  3.089455e-06  2.984148e-06  2.793931e-06  2.768266e-06   
       251  0.000002  2.853915e-06  2.776518e-06  2.634487e-06  2.613137e-06   
       252  0.000001  2.684522e-06  2.624091e-06  2.510512e-06  2.491699e-06   
       253  0.000001  2.504611e-06  2.460653e-06  2.376806e-06  2.361599e-06   

group                                                               \
id                   249           250           251           252   
group  id                                                            
DIS NC 0    2.348319e-08 -5.652816e-08 -1.474185e-07 -2.101223e-07   
       1    2.869618e-07 -5.979509e-08 -3.072188e-07 -4.368175e-07   
       2    1.561670e-06  1.449590e-06  1.320671e-06  1.233540e-06   
       3    1.287081e-06  1.073367e-06  8.940779e-07  7.843064e-07   
       4    4.770826e-07  3.440389e-07  2.206730e-07  1.384722e-07   
...                  ...           ...           ...           ...   
       249  4.316390e-06  2.597004e-06  2.482546e